### ISSUE TITLE
remove Office file versions of LabPractical documents?

### ISSUE THREAD

**Issue by davidbradway** [mlp6/IntroBiomedicalElectronics#12]

**Comment by mlp6** [comment]
Yes please!

**Comment by mlp6** [comment]
I realized that most of the spreadsheets were just tables w/ student names from that specific semester; that was less useful than I remembered.  I the DOCX file that was converted really the only one of substance?

**Comment by davidbradway** [comment]
I will preserve Matt's comments from the DOCX file, remove the Office files, and remove the student names from all the files. I will keep this thread open for review.
