### ISSUE TITLE
add Grader's info to the Syllabus and repository?

### ISSUE THREAD

**Issue by davidbradway** [mlp6/IntroBiomedicalElectronics#15]
Monique Goldsmith 
monique.goldsmith@duke.edu

**Comment by mlp6** [comment]
Sometimes I hide who this is from the students so that they don't try to circumvent due dates and submit directly to that person, or grade complain to them.  Not sure if that might be a moot point for this class.  Thoughts?

**Comment by sayanroyc** [comment]
I'd lean towards hiding since any assignment issues should be brought to one of us before it goes back to the grader, but I have no experience here.

**Comment by sphaerobolus** [comment]
Students will approach everyone they can think of in search of a better grade. I've witnessed them shopping their case around the BME354 lab TAs, then me, then....

**Comment by davidbradway** [comment]
Agreed. Closing this issue.
