### ISSUE TITLE
I need a textbook

### ISSUE THREAD

**Issue by davidbradway** [mlp6/IntroBiomedicalElectronics#19]

**Comment by mlp6** [comment]
My slightly-older-edition version of Art of Electronics and Practical Electronics for Inventors should be in the Chesterfield lab (may be the design suite side).  You can have those.  You can also ask Cindy if she can request an instructors copy for you, or you can direct solicit an instructors copy from the publisher.

**Comment by davidbradway** [comment]
I have Gregg's 2nd Ed AoE. I'll look at the PEFI book and ask Cindy about a new copy. Thanks
