### ISSUE TITLE
convert documents on `lab_practical` branch to Markdown

### ISSUE THREAD

**Issue by mlp6** [mlp6/IntroBiomedicalElectronics#5]

**Comment by davidbradway** [comment]
do you mean on that branch in that folder? 
`IntroBiomedicalElectronics/LabPractical (lab_practical)
$ ls
BreadboardSchematic.xlsx  CurrentMeasurement.xlsx  LabPracticalExam.docx  OscilloscopeSetup.xlsx  PowerSupplySetup.xlsx
`
I can turn them into Markdown tables if that's what you are after

**Comment by mlp6** [comment]
Yep - any format that will render nicely via the web (especially the DOCX file).
