### ISSUE TITLE
integrate Piazza into Sakai site

### ISSUE THREAD

**Issue by mlp6** [mlp6/IntroBiomedicalElectronics#9]

**Comment by davidbradway** [comment]
Will @mlp6 handle opening the Piazza site or should I figure it out?

**Comment by mlp6** [comment]
I'll take care of it; working on Sakai tool integration now.

**Comment by mlp6** [comment]
Piazza should be live for the class, with a button in the left-hand navigation bar on the Sakai site.  @davidbradway do you mind enrolling all of the students?

**Comment by davidbradway** [comment]
ok, 14 enrolled. 3 already have Piazza accounts.
